version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: barberBoss_db   
    environment:      
      MYSQL_DATABASE: barberBoss     
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork:
    driver: bridge
